/**
 * Pick Voice
 * Api para el sistema Pick Voice, plataforma que optimiza los procesos logisticos de un centro de distribucion, implementando tecnologia por voz.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabriel.martinez@tau-tech.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Location {
    /**
     * codigo de la ubicacion
     */
    code: string;
    /**
     * session del almacen
     */
    sections?: string;
    /**
     * pasillo a la cual pertenece la ubicacion
     */
    lane?: string;
    /**
     * columna del rack
     */
    column?: string;
    /**
     * altura de la ubicacion la cual es dependiente del nivel del rack
     */
    height?: string;
    /**
     * profundidad
     */
    deep?: string;
    /**
     * codigo de seguridad de la ubicacion
     */
    checkDigits?: number;
}
