/**
 * Pick Voice
 * Api para el sistema Pick Voice, plataforma que optimiza los procesos logisticos de un centro de distribucion, implementando tecnologia por voz.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabriel.martinez@tau-tech.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Item } from './item';
import { Location } from './location';
export interface OrderLine {
    item?: Item;
    /**
     * Cantidad reservada a pickear por este ítem.
     */
    qtyToPicked?: number;
    expiryDate?: string;
    serial?: string;
    batchNumber?: string;
    location?: Location;
    /**
     * Bandera que indica si un ítem es un elemento de base (sin tener en cuenta su peso y cantidad).
     */
    baseItemOverride?: boolean;
    /**
     * Si se utiliza la etiqueta caso dígitos de control, este valor que debe ser especificado por el operador para asegurarse de que la etiqueta apropiada será puesta en un contenedor.
     */
    caseLabelCheckDigits?: boolean;
    /**
     * codigo del LPN de donde recogen el item en el pick
     */
    cartonCode?: string;
    /**
     * Especifica el orden en que el Pick Voice selecciona e indica los picks para un operador.
     */
    pickSequenceNumber?: number;
    /**
     * codigo de trabajo que pertenece la linea de recogida
     */
    workCode?: string;
    /**
     * Cantidad recogida por ese ítem.
     */
    qtyToPacked?: number;
}
