/**
 * Pick Voice
 * Api para el sistema Pick Voice, plataforma que optimiza los procesos logisticos de un centro de distribucion, implementando tecnologia por voz.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabriel.martinez@tau-tech.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Customer } from './customer';
import { OrderLine } from './orderLine';
import { Transport } from './transport';
export interface Order {
    /**
     * Identificador único para una orden o pedido.
     */
    orderNumber: string;
    /**
     * El formato debe ser DD/MM/YYYY
     */
    deliveryDate?: string;
    route: Transport;
    customer: Customer;
    orderLine: OrderLine;
    /**
     * Meta de tiempo para completar esta tarea, la naturaleza del campo es horas
     */
    goalTime?: number;
    /**
     * La fecha en que el camión va a salir del almacén.
     */
    departureDateTime?: string;
    /**
     * trabajo primario a la cual pertenece la orden
     */
    rootWorkCode?: string;
}
