/**
 * Pick Voice
 * Api para el sistema Pick Voice, plataforma que optimiza los procesos logisticos de un centro de distribucion, implementando tecnologia por voz.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gabriel.martinez@tau-tech.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Transport {
    /**
     * Numero del transprote del tms (SAP).
     */
    transportNumber?: string;
    /**
     * Ruta o número de transporte asociada a la orden.
     */
    route?: string;
    name?: string;
    /**
     * Refiere a la puerta por donde se despachar el transporte.
     */
    dispatchPlatforms?: string;
    /**
     * Codigo del tranportador
     */
    carrierCode?: string;
    /**
     * Status del transporte
     */
    transportState?: Transport.TransportStateEnum;
}
export declare namespace Transport {
    type TransportStateEnum = 'Pending' | 'InProgress' | 'Complete';
    const TransportStateEnum: {
        Pending: TransportStateEnum;
        InProgress: TransportStateEnum;
        Complete: TransportStateEnum;
    };
}
